# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramorie < Formula
  desc "AI-powered task and memory management CLI"
  homepage "https://ramorie.com"
  version "4.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kutbudev/ramorie-cli/releases/download/v4.0.5/ramorie_4.0.5_darwin_amd64.tar.gz"
      sha256 "8b96b4e2cd647c99c3e7ff0c86eb49abab452f0ce3fa6d2e8445bd07090e165f"

      def install
        bin.install "ramorie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kutbudev/ramorie-cli/releases/download/v4.0.5/ramorie_4.0.5_darwin_arm64.tar.gz"
      sha256 "e678c7c37f55f2915fcd4a6af71dd2ea143a2ca9246d5f5eb6c82f2891178ae6"

      def install
        bin.install "ramorie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kutbudev/ramorie-cli/releases/download/v4.0.5/ramorie_4.0.5_linux_amd64.tar.gz"
      sha256 "24707dbcaf392721dbeece4ab2b854999ce9d092b837a40dcc79e94703b48f49"
      def install
        bin.install "ramorie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kutbudev/ramorie-cli/releases/download/v4.0.5/ramorie_4.0.5_linux_arm64.tar.gz"
      sha256 "26a8ae12c27f1f01cdde6cfbf0869e2c4f21a7282591368438faa0995e0fd9ee"
      def install
        bin.install "ramorie"
      end
    end
  end

  test do
    system "#{bin}/ramorie", "--version"
  end
end
